### ISSUE TITLE
Host Project

### ISSUE THREAD

**Issue by raman08** [ritikalohia/HOVER1-#1]
It would be nice to host the project so that person hovers the buttons himself or herself. 

You can use the GitHub hosting service for this. :blush: :blush:

**Comment by ritikalohia** [comment]
I really want to host, but in GitHub  we can only host the project with the
name of index.html file, and I think it is limited to only 1 website=1repo
and in this repo, I have included 12 different pages with different name(
assigned in readme also).
But you can check my other repo, they are hosted perfectly 🤘😄🤘.

**Comment by raman08** [comment]
It is true that you can make only one site per repo. But you can make some changes in the index.html file and add all those buttons in it with some CSS styling. It will make some beautiful changes to the repo and if you want you can add the source code of the button with it.
You see this will make it easy for developers to see the effect itself

**Comment by ritikalohia** [comment]
Thanks, I'll check it out.
